[package]
edition = "2021"
name = "backtracetk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8.1"
termcolor = "1.2.0"
